language: node_js
node_js:
  - '0.10'

install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt petal-dist

deploy:
  provider: s3
  bucket: shakr-petal
  access_key_id:
    secure: "ub2ProVLegi7o+ucozjacVhLcYmRg0XEdNQ2eh8bnXkos2+oxc4ZXM/f5cnW65mhHkj8En8dHJGCg1+wqcdH1ow0zqDb1hDzXy4sz++JekoC6NCM0XSSHhmgZOzDXppTC3YsQhnjvjZ/cVjvOmfvrtX+wI36QaJLFLN9tTXcWdnFWeLPRlwfAlbyuWK1CH8/uChf+WubqbrkmpS3aOIoUFz6/2IKrdCiQrByavVPI92TmKQwkMZMI0f8leKZaOsbp2dfDWzTQckXodWUsDUlTJN3v/RP6QVTDH8Qj0O/NHr7PMkha352j/VylCwK7UiSy1tkpW7qX65qC62Py1r/u4tKbbHv6JXr5DpccETb5jSQ25ULXEKJhCqEDS5v3i8JeoSIwQ+gAiLC+VR9rLqCOgFL91GHGddWY8+b3IJ4uBjLMacP2aQdC0KFgIkmH1K3KH9fNTcJYY5GqpjNNCr9wTX5H8igwicAglkwbwC8/bTZEJ13CaPTlw+rBtECT8Y7+04ulWUH9PHKReq9CPIuSwCsiZtKLQXAKnx/X2DQQ36UZNB/+MZh0GJbzGmGjr3OasNHs5gJQ6uq254+DPp1GIvEbDnhAEUYJukV2uvMKqIYCd7vobVD6v5SI2YFJ7tT2+A4aXQTzGkIrg9uzod0fq8LADNTnLlONFkmQRnpGyc="
  secret_access_key:
    secure: "j9bg/qmDl/4iVI/a7Z7gZnmpT5RK3RvqXFdYXWpQIH+y7LcNEPmwuQ+ILQCdU3yX6jvHOSX0jO7PLzuJ2DU8abw9SFBp+poPdUJUjs3UD37QzH/eri/OHcw8XNPrEYkZGqphJVrYxQId9En2O7DUNp5C1E6sIhDv/+iZ/XUuqliyxDd0A5LebIhcLgG/PARgUlmkdWEdrriftryNtQAaZSY2JPEY6wOzk7NnzHBr3UMZCC8qFW+vxcfPBL1fejc1OaZ5L1XPvEACn7Q5L11wOV9wkVtkn/WurATwpRLEZK+mMVt5v3HXSUwFFl4fXt5S2KhMLVT5NP6YqVVGvqIxt89CpgaAtJAfZXyuH15o/dwBRRwb3x/5P1M8HGHETCr0RgdiBv+nGEVkAZBdUCV6GjBFiVp14O6WaM9sgCS8fIa9CIngB/978St6ZsOd6+OgVcOJeb4a1SSRTjFd25Vt8xGtfU8VyOLEhNdBCbymbzPKVNXepeb8Rsth0au+ifSXmFutx4EKLoaJABduibWqup8lv7GY8lkzNKRT96eEsAisqaD8F+UVrl2k95F9O+6LPIEMV7XwB23z5T4VyW99i2k1bn1mmL52kizo7ktPtBCzFPYhHRzlnWwwFfdVqIW5Ouf3+G1UZxzxYF4o8ynhIJq1eOnrzjaPh8hUEKUStlQ="
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-1
  local_dir: _dist
  upload_dir: edge
