language: node_js
node_js:
  - '0.10'

install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt petal-dist

deploy:
  provider: s3
  bucket: shakr-petal
  access_key_id:
    secure: "VyaEBqizrRqOi3EfMXJ8AITZtd5rC3aUcg1o3QRDxReq/IKKbnD5CE4Z47f6wUqLcfPY1bryEUfsC8AV5iPz4x4EJIfu+BkFYtsQ3HhS/2sSBhx+DRvZnTlB1wWJGoJSFZ7K7qd3p8e4jTdXiimQT9A2Mef2OKZiRKjn6aSCd+pfUPRxMCXKSZfA+TXwW9/Ood5CBN+6O5kZ98KUMVqhFOAkYuyIXEmNMAMaOhpS4WaswgiMYGS/MUxZZG3xCKyYGUxtrmNdezT7f4qX6K1yHWzjk7f6eZvaWCsSipLTTtV4BTFD2PfnUGbuXFlw7sVcx8xW7KR2+yGdZxq5ZghdTm5VwUdvAAbfvyjhbxKLlHZ9qMlirc6C+uG4M7vWrN/z6NPJULA/l+ycUjT2NrtrIVmefk2QFt6LmbThVrI7XY8gNgESfQNIOxisPzbzCKcsEGH8JmuTvvKkWytacK0uTqJgQOjUP8SRM29F4jlOKksQ7+58KvnOzq8p2YMyTlyBt9kGY7piXkj0IVtjTgOj7s/X7TdKwoYGaLomZIHxApnRi+qrz1dBuueMkLRGyrluir9gsy8zAH1hSlvOVVDSaU91uqV5Ky+lTIX0yrpKbFtiUF2mTAIYmnSPMYsEx13YyXivparQljRDcFa9atUPJq1ubr/TnkyF8LehQZRXhIE="
  secret_access_key:
    secure: "Xd/rP5L8/3iO7iNEmBcE5OBzaoGGc9oCE8bq2w0t1kW5FleTUWRtJ+z4OdMmpWFeiRCp6oEThk7r3flUm4JwLQGOJjwPkfgTalY36stM9B/JlKHRompFIXuG1VReLNlBzkITOI/cgMxZzfKT1PIcqlP2KfhaMlzPBmlZCCl6js/qZoO2D4Hscw2DYhC4aEwuVhMflAuu6nFlgd0kZTckU0otDHkhy78ZAm5x4VmLoekv3AfGnGIuq5S14SqjVui0AbEegh4YHHVBE09OwQdCMUKsMbzx4mTN5KyWL517vV7vlrUejIeiLO+DU+UZJ3A3t0nfGvTSv81bM6KaeRUaAtVmSdnFwPC9mdyPby0648bEcM0PlCPPrEVmUVyeLOSazwz74/KXZG/Hw1KlSPXZ8ND6sMl4IDqp5cTj3hwoYcM4Z8/272U1RQiLetg1hYRk2YYn4ahvT28kcBnzK4tUpIqri2MkbNnZk7/sxhDzVFJUO9xUVMPfdpnWjOJUL0x5pVeFGEBDynkKesmFeaipHxaSZ2N8jC8a/XgmiSkoc6eOqwSGVZd5RoSUQshsxyGPGZxQznCgrceiGmwPTKZ5BHZca9IvhEnscFbrYSJQPEoVR+QgKszjds/mvlRJvAhQISJt1EMrcCSCVWtc4mdagAZaiOFiE8oZLYlPrIMpPsc="
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-1
  local_dir: _dist
  upload_dir: edge
